---
name: Unit-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  get-image-link:
    runs-on: ubuntu-latest
    outputs:
      fedora_image_link: ${{ steps.set-image-link.outputs.image_link }}
    steps:
      - uses: actions/checkout@v4
      - id: set-image-link
        run: |
          IMAGE_LINK=$(cat Containerfile | grep FROM | cut -d ' ' --fields=2)
          echo "image_link=$IMAGE_LINK" >> $GITHUB_OUTPUT

  run-python-unit-tests:
    needs: get-image-link
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.get-image-link.outputs.fedora_image_link }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: install needed RPMs
        run: dnf install -y python3-norpm python3-pip python3-specfile koji patch git rpmlint

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install test dependencies
        run: pip install -r test_requirements.txt

      - name: Run unit tests
        run: ./run_tests.sh
