---
name: Unit-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-python-unit-tests:
    runs-on: ubuntu-latest
    container:
      image: fedora:43

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: install needed RPMs
        run: dnf install -y python3-norpm python3-specfile python3-pip koji patch git

      - name: patch rpmdiff
        run: patch /usr/lib/python3.14/site-packages/koji/rpmdiff.py < rpmdiff.patch

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install test dependencies
        run: pip install -r test_requirements.txt

      - name: Run unit tests
        run: ./run_tests.sh
